name: GitHub Actions Demo
on:
    push:
        branches: [third]
    pull_request:
        branches: [third]
jobs:
    init:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-varsion: [16.x]
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install deps
              run: npm install
            - name: Test app
              run: npm run test
            - name: Lint code
              run: npm run lint
            - name: Build App
              run: npm run build
